# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NebulaDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NebulaDemo

  # NebulaCore
  pod 'NebulaCore2', :git => 'https://www.t5online.com:8002/t5-frameworks/nebula.git'

  # Nebula Modules
  pod 'PreferenceModule', :git => 'https://github.com/t5online-inc/Nebula_PreferenceModule.git'
  pod 'DeviceInfoModule', :git => 'https://github.com/t5online-inc/Nebula_DeviceInfoModule.git'
  pod 'ScreenShotModule', :git => 'https://github.com/t5online-inc/Nebula_ScreenShotModule.git'
  pod 'StatusBarModule', :git => 'https://github.com/t5online-inc/Nebula_StatusBarModule.git'
  pod 'FileSystemModule', :git => 'https://github.com/t5online-inc/Nebula_FileSystemModule.git'
  pod 'GeolocationModule', :git => 'https://github.com/t5online-inc/Nebula_GeolocationModule.git'
  pod 'BioAuthenticationModule', :git => 'https://github.com/t5online-inc/Nebula_BioAuthenticationModule.git'

end
